version: '3.8'

services:
  nestjs-app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis-sessions

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  redis-sessions:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - sessions:/data

volumes:
  db:
  sessions: