version: '3.8'

services:
  nestjs-app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"