version: '3.8'

services:
  nextjs-app:
    container_name: dev-the-room-frontend
    build:
      context: ./frontend
      target: dev
    env_file:
    - ./frontend/.env.dev
    expose:
      - "8080"  # Internal Docker network port
    command: npm run dev --reload
    volumes:
      - ./frontend:/app
    depends_on:
      - nestjs-app
  
  nestjs-app:
    container_name: dev-the-room-backend
    build: 
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    expose:
      - "3000"
    command: npm run start:dev --reload
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
      - redis-sessions

  mongo:
    container_name: dev-the-room-db
    image: mongo:7
    environment:
    - MONGO_INITDB_DATABASE=the-room
    expose:
      - "27017"
    volumes:
      - dev-app-volume:/data/db

  redis-sessions:
    container_name: dev-the-room-sessions-storage
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - dev-app-volume:/data

  nginx:
    container_name: dev-the-room-reverse-proxy
    image: nginx:latest
    ports:
      - "80:80"   # HTTP port
      - "443:443" # HTTPS port
    depends_on:
      - nestjs-app
      - nextjs-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./ssl:/etc/nginx/ssl # Directory for SSL certificates

volumes:
  dev-app-volume: